/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2024-03-16 18:40:31 
*/
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";
import { FormBuilder, FormControl, FormGroup, Validators } from "@angular/forms";
import { AlertaService } from "../services/AlertaService";

export interface IRegistrarEventoPage {
    fb: FormBuilder;
    FormularioEvento: FormGroup<any>;
    fechaActual: any;
    fechaISO: string;
    horaActual: string;
    ngOnInit(): void;
    agregarevento(): any;
    agregar(): void;
    ionViewDidLeave(): void;
}
